config/routes.rb
Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  root "restaurants#index"

  resources :restaurants do
    resources :reviews, only: [:create]
  end
  resources :reviews, only: [:show, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, :rating, presence: true
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[show edit update destroy]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant, notice: "Restaurant was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: "Restaurant was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path, notice: "Restaurant was successfully destroyed."
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %i[create]

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      redirect_to restaurant_path(@restaurant), alert: "Erro ao adicionar review."
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant), status: :see_other
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.6/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4Q6Gf2aSP4eDXB8Miphtr37CMZZQ5oXLH2yaXMJ2w8e2ZtHTl7GptT4jmndRuHDT" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="container py-4">
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Restaurantes</h1>

<%= link_to "Novo restaurante", new_restaurant_path, class: "btn btn-success mb-3" %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Categoria</th>
      <th>Telefone</th>
    </tr>
  </thead>
  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= link_to restaurant.name, restaurant_path(restaurant) %></td>
        <td><%= restaurant.category %></td>
        <td><%= restaurant.phone_number %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>

<%= simple_form_for @restaurant do |f| %>
  <div class="mb-2">
    <%= f.input :name %>
  </div>
  <div class="mb-2">
    <%= f.input :address %>
  </div>
  <div class="mb-2">
    <%= f.input :phone_number %>
  </div>
  <div class="mb-2">
    <%= f.input :category, collection: ["chinese", "italian", "japanese", "french", "belgian"], prompt: "Choose a category" %>
  </div>
  <%= f.submit "Save", class: "btn btn-success" %>
<% end %>

<%= link_to "Back", root_path, class: "btn btn-secondary mt-2" %>

app/views/restaurants/show.html.erb
<h1><%= @restaurant.name %></h1>
<p><strong>Category:</strong> <%= @restaurant.category %></p>
<p><strong>Phone:</strong> <%= @restaurant.phone_number %></p>
<p><strong>Address:</strong> <%= @restaurant.address %></p>

<h2>Reviews</h2>
<% if @restaurant.reviews.any? %>
  <ul class="list-group mb-3">
    <% @restaurant.reviews.each do |review| %>
      <li class="list-group-item">
        <%= review.content %> 
        <% review.rating.times do %>
          <i class="fa-solid fa-star"></i>
        <% end %>
        <% (5 - review.rating).times do %>
          <i class="fa-regular fa-star"></i>
        <% end %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>Don't have any reviews yet!.</p>
<% end %>


<h3>Add Review</h3>
<%= simple_form_for([@restaurant, Review.new]) do |f| %>
  <div class="mb-2">
    <%= f.input :content %>
  </div>
  <div class="mb-2">
    <%= f.input :rating, as: :integer, input_html: { min: 0, max: 5 } %>
  </div>
  <%= f.submit "Submit Review", class: "btn btn-primary" %>
<% end %>

<%= link_to "Back", root_path, class: "btn btn-secondary mt-3" %>

app/views/reviews/new.html.erb
<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>